### PR TITLE
Project set up

### PR DESCRIPTION
**Pull request by richardoppiyo**
This pull request is for the required project set-up  and addition of the required files in the Hello world project

### CODE REVIEW

**Review by aliabbani — CHANGES_REQUESTED** [review]
Hi @richardoppiyo ✋, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! 

To Highlight! 🟢
You created a new GitHub repo. ✔️
You created a new branch according to the GitHub flow rules. ✔️
You added a .gitignore file. ✔️
You opened your first pull request. ✔️
You wrote meaningful commit messages. ✔️

## Required Changes ♻️ 

Check the comments under the review. 

- [ ] Please add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- [x] Please Set up a linter correctly. Please check [this link ](https://github.com/microverseinc/linters-config/tree/master/html-css) for more information. Also, please make sure that the Linter result is green on the pull request. Linter should always report no errors and show green when you submit a future pull request (on your pull request the Webhint and Stylelint is showing ❌).
- [x] Please add a short summary describing introduced changes in more detail in your pull request. you can see where to add the comment in the image below 

image
Please check [this link](https://www.google.com/url?q=https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md&sa=D&source=docs&ust=1641319160035085&usg=AOvVaw1HziA0S51s6bo-2UWGSx2H) for more information.

## Optional suggestions 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by aliabbani — CHANGES_REQUESTED** [review]
Hi, @richardoppiyo ✋>, 

Great work on making the changes requested. 👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] Please add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by micheaol — APPROVED** [review]
# STATUS: APROVED :green_circle: :clap: 
Hi @richardoppiyo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥇 
Congratulations! 🎉 

well-1

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by eliasecasta — COMMENTED** [review]
Hello @richardoppiyo 👋,

_This is an additional review as a result of the second opinion request._

Everything seems to be sorted out in this PR, good luck with your next projects!

Keep rocking 🚀!

**Pull request merged**
